name: PHPCS Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

permissions:
  actions: read
  checks: read
  contents: read
  statuses: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
    - uses: actions/github-script@v6
      with:
        script: |
          const { execSync } = require('child_process')
          const { commits } = context.payload.pull_request
          const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
          const files = rawFiles.split('\n').filter(Boolean)
          console.log(files)

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run PHPCS
      run: composer phpcs
